### ISSUE TITLE
Demos and docs?

### ISSUE THREAD

**Issue by ianozsvald** [matplotlib/trendvis#17]
Hello. I'm interested in trying this (I just watched the SciPy 2015 video) but I don't see any docs. Where should I be looking? 

I got as far as cloning and running `python setup.py install` (which worked fine) and `python run_tests.py` (they all passed). I see `test_trendvis.py` but that makes empty plots, right?

Perhaps you could provide a small getting-started guide in the README for a trivial plot?

**Comment by mscross** [comment]
`test_trendvis.py` is the test suite. I'm still working on the official docs, but for now (#18) here are some examples in `README.md`.  I think they cover the majority of features.  Putting this together has also helped me find bugs (#19), so thanks for bringing this up (and please pull down the fixes!).  Hope this helps!

**Comment by ianozsvald** [comment]
Many thanks Mellissa, I have it running in Py3, cheers :-)
